AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL database for Customer360 (CRM)

Parameters:
  DBName:
    Type: String
    Default: crm
  MasterUsername:
    Type: String
    Default: admin
  MasterUserPassword:
    Type: String
    NoEcho: true
  AllocatedStorage:
    Type: Number
    Default: 20
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id

Resources:
  ## Security group to allow MySQL access from DMS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access from DMS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0  # for demo; tighten later
      Tags:
        - Key: project
          Value: customer360

  ## Subnet group
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS MySQL
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
        - Key: project
          Value: customer360

  ## The MySQL instance
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: customer360-crm-db
      Engine: mysql
      EngineVersion: "8.0"
      DBName: !Ref DBName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      PubliclyAccessible: true
      MultiAZ: false
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref RDSSubnetGroup
      BackupRetentionPeriod: 1
      DeletionProtection: false
      Tags:
        - Key: project
          Value: customer360

Outputs:
  RDSInstanceEndpoint:
    Description: The RDS MySQL endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
  RDSSecurityGroupId:
    Description: Security Group ID for RDS MySQL
    Value: !Ref RDSSecurityGroup
